name = "/Users/benoitsierro/tests/test_sc/Chang2011Fig2"

wavelength = 800e-9
shape = "gaussian"
energy = 2.5e-6
width = 30e-15

core_radius = 10e-6
model = "marcatili"
gas_name = "argon"
pressure = 1e5

length = 0.1
interpolation_range = [100e-9, 3000e-9]
full_field = true
dt = 0.1e-15
t_num = 32768
z_num = 128
step_size = 2e-6
