nam)e = "full anomalous"

# fiber
beta2_coefficients = [
    -1.183e-26,
    8.1038e-41,
    -9.5205e-56,
    2.0737e-70,
    -5.3943e-85,
    1.3486e-99,
    -2.5495e-114,
    3.0524e-129,
    -1.714e-144,
]
gamma = 0.11
length = 0.02

# pulse
peak_power = 10000
t0 = 2.84e-14

# simulation
dt = 1e-15
parallel = true
raman_type = "measured"
repeat = 4
t_num = 16384
tolerated_error = 1e-10
z_num = 64

[variable]
# pulse.variable
wavelength = [835e-9, 830e-9]
