# raman_type should be added

name = "test config"

# fiber
gamma = 0.018
length = 1
model = "pcf"
pitch = 1.5e-6
pitch_ratio = 0.37

# pulse
peak_power = 100e3
quantum_noise = true
shape = "gaussian"
wavelength = 1050e-9
width = 50e-15

# simulation
behaviors = ["spm", "raman", "ss"]
parallel = true
repeat = 4
t_num = 16384
time_window = 37e-12
tolerated_error = 1e-11
z_num = 128

[variable]
# pulse.variable
intensity_noise = [0.10000000005e-2, 0.1e-2]
