name = "test config"

# fiber
length = 1
model = "pcf"
pitch = 1.5e-6
pitch_ratio = 0.37

# pulse
field_file = "testing/configs/custom_field/init_field.npz"
quantum_noise = false

# simulation
behaviors = ["spm", "raman", "ss"]
lower_wavelength_interp_limit = 300e-9
raman_type = "agrawal"
t_num = 16384
time_window = 37e-12
tolerated_error = 1e-11
upper_wavelength_interp_limit = 1900e-9
z_num = 128

[variable]
# pulse.variable
wavelength = [1050e-9, 1321e-9, 1593e-9]
