name = "full anomalous"

[fiber]
beta = [-1.183e-26, 8.1038e-41, -9.5205e-56, 2.0737e-70, -5.3943e-85, 1.3486e-99, -2.5495e-114, 3.0524e-129, -1.714e-144]
gamma = 0.11
input_transmission = 1.0
length = 0.02
model = "custom"

[pulse]
intensity_noise = 0
peak_power = 10000
quantum_noise = false
shape = "gaussian"
t0 = 2.84e-14

[simulation]
behaviors = ["spm", "ss"]
dt = 1e-15
frep = 80000000.0
ideal_gas = false
lower_wavelength_interp_limit = 3e-7
parallel = true
raman_type = "measured"
repeat = 3
t_num = 16384
tolerated_error = 1e-9
upper_wavelength_interp_limit = 1.9e-6
z_num = 64

[pulse.variable]
wavelength = [8.35e-7, 8.3375e-7]
